### ISSUE TITLE
Remove "gasPrice" from TradeInfo schema

### ISSUE THREAD

**Issue by L-Kov** [ParadigmFoundation/zaidan-dealer-specification#55]
While some information that is included in the current TradeInfo schema is relevant/helpful, the explicit definition of `gasPrice` is restricting for the dealer. On relatively large/valuable orders, or for low reputation takers, the dealer will likely want to have flexibility on the gas price value. As such, we should remove `gasPrice` from the `TradeInfo` schema.

**Comment by hrharder** [comment]
> This is tricky -- because in 0x v3 the gas price is part of the data the taker must sign in their transaction, it is important that data is available. 

If not here, at least in the quote that is provided.

**Comment by hrharder** [comment]
The main point is the taker **needs** to know the gas price at the time the quote is provided, because it must be included in the signature.

So either way, we will need to send the gas price to the taker with the quote, either in the `TradeInfo` object or as part of the top-level `Quote` itself.
